### ISSUE TITLE
ImportError: No module named envie.utils

### ISSUE THREAD

**Issue by jayvdb** [randomir/envie#9]
I installed it via an RPM https://build.opensuse.org/package/show/home:jayvdb:py-new/python-envie

```console
~/tmp> . /usr/bin/envie
~/tmp> envie
Traceback (most recent call last):
  File "/usr/bin/envie-tools", line 11, in <module>
    from envie.utils import readlink, realpath
ImportError: No module named envie.utils
^CTraceback (most recent call last):
  File "/usr/bin/envie-tools", line 11, in <module>
    from envie.utils import readlink, realpath
ImportError: No module named envie.utils
^CTraceback (most recent call last):
  File "/usr/bin/envie-tools", line 11, in <module>
    from envie.utils import readlink, realpath
ImportError: No module named envie.utils
^CTraceback (most recent call last):
  File "/usr/bin/envie-tools", line 11, in <module>
    from envie.utils import readlink, realpath
ImportError: No module named envie.utils
^CNo environments found.
~/tmp> head /usr/bin/envie-tools
#!/usr/bin/python3 -s
from __future__ import print_function
import os
import sys

# ensure `envie` is accessible, without being installed via pip:
scriptsdir = os.path.dirname(os.path.abspath(__file__))
projectroot = os.path.normpath(os.path.join(scriptsdir, os.pardir))
sys.path.insert(0, projectroot)

~/tmp> python3 -c 'import envie.utils'
```

**Comment by randomir** [comment]
Thank you for reporting this, and for creating an RPM! I’ll look into this shortly.
